apiVersion: v1
kind: Secret
metadata:
  labels:
    app: prometheus-7.3.0
  name: prometheus-config
  namespace: monitoring
type: Opaque
stringData:
  prometheus-additional.yaml: |
{{ $.Files.Get (printf "%s" "prometheus-config/prometheus-additional.yaml") | indent 4 }}