{{- range .Values.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    istio-injection: {{ if eq . "service" }}enabled{{ else }}disabled{{ end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: hubsecret
  namespace: {{ . }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "{{ $.Values.dockerRegistry.server }}": {
          "username": "{{ $.Values.dockerRegistry.username }}",
          "password": "{{ $.Values.dockerRegistry.password }}",
          "auth": "{{ printf "%s:%s" $.Values.dockerRegistry.username $.Values.dockerRegistry.password | b64enc }}"
        }
      }
    }

---
{{- end }}
