apiVersion: batch/v1
kind: Job
metadata:
  name: kubeflow-crd-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: istio-installer
      containers:
      - name: setup
        # 使用你的自定义镜像，假设镜像标签为my-kubectl-with-istio:latest
        image: gaoxin2020/kubectl-cube:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          kubectl apply -f /training-crd/
      restartPolicy: Never

