apiVersion: batch/v1
kind: Job
metadata:
  name: istio-setup
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: istio-installer
      containers:
      - name: setup
        # 使用你的自定义镜像，假设镜像标签为my-kubectl-with-istio:latest
        image: gaoxin2020/kubectl-cube:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          kubectl apply -f /istio/install-crd.yaml
          kubectl wait crd/envoyfilters.networking.istio.io --for condition=established --timeout=60s
          kubectl apply -f /istio/install-1.15.0.yaml
          kubectl wait crd/virtualservices.networking.istio.io --for condition=established --timeout=60s
          kubectl wait crd/gateways.networking.istio.io --for condition=established --timeout=60s
          kubectl apply -f /istio/gateway.yaml
          kubectl apply -f /istio/virtual.yaml
          kubectl patch svc istio-ingressgateway -n istio-system -p '{"spec":{"externalIPs":["'"{{ .Values.nodeLabels.nodeIP }}"'"]}}'
      restartPolicy: Never
