apiVersion: batch/v1
kind: Job
metadata:
  name: create-virtual-service
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: istio-installer  # 使用有足够权限的 Service Account
      restartPolicy: Never
      containers:
      - name: kubectl
        image: gaoxin2020/kubectl-cube:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          kubectl apply -f - <<EOF
          apiVersion: networking.istio.io/v1alpha3
          kind: VirtualService
          metadata:
            name: infra-kubeflow-dashboard
            namespace: infra
          spec:
            gateways:
            - kubeflow/kubeflow-gateway
            hosts:
            - "*"  # 适当替换为实际的域名
            http:
            - route:
              - destination:
                  host: kubeflow-dashboard-frontend.infra.svc.cluster.local
                  port:
                    number: 80
          EOF
