"""empty message

Revision ID: 552b16a617a9
Revises: 95c1b06d75e9
Create Date: 2024-09-11 18:35:37.192953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '552b16a617a9'
down_revision = '95c1b06d75e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ab_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ls_user_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('docker', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('etl_pipeline', schema=None) as batch_op:
        batch_op.alter_column('dag_json',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='pipeline的上下游关系',
               existing_nullable=True)
        batch_op.alter_column('config',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='pipeline的全局配置',
               existing_nullable=True)
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('etl_task', schema=None) as batch_op:
        batch_op.alter_column('task_args',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='任务参数',
               existing_nullable=True)
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('inferenceservice', schema=None) as batch_op:
        batch_op.alter_column('model_input',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='模型输入',
               existing_nullable=True)
        batch_op.alter_column('model_output',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='模型输出',
               existing_nullable=True)
        batch_op.alter_column('inference_config',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='配置文件',
               existing_nullable=True)
        batch_op.alter_column('metrics',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='监控接口',
               existing_nullable=True)
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)
        batch_op.alter_column('deploy_history',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='部署历史',
               existing_nullable=True)

    with op.batch_alter_table('job_template', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('metadata_metric', schema=None) as batch_op:
        batch_op.alter_column('caliber',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='数据负责人',
               existing_nullable=True)
        batch_op.alter_column('remark',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('metadata_table', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('notebook', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.alter_column('pipeline_file',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=655360),
               existing_comment='workflow yaml文件',
               existing_nullable=True)
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)
        batch_op.alter_column('parameter',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='前端保留参数，用于记录编排样式',
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('pytorchjob', schema=None) as batch_op:
        batch_op.alter_column('spec',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=655360),
               existing_comment='配置详情',
               existing_nullable=True)

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.alter_column('pipeline_file',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=655360),
               existing_comment='workflow yaml',
               existing_nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65536),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('tfjob', schema=None) as batch_op:
        batch_op.alter_column('spec',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=655360),
               existing_comment='配置详情',
               existing_nullable=True)

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.alter_column('spec',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=655360),
               existing_comment='配置详情',
               existing_nullable=True)

    with op.batch_alter_table('xgbjob', schema=None) as batch_op:
        batch_op.alter_column('spec',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=655360),
               existing_comment='配置详情',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xgbjob', schema=None) as batch_op:
        batch_op.alter_column('spec',
               existing_type=sa.Text(length=655360),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='配置详情',
               existing_nullable=True)

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.alter_column('spec',
               existing_type=sa.Text(length=655360),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='配置详情',
               existing_nullable=True)

    with op.batch_alter_table('tfjob', schema=None) as batch_op:
        batch_op.alter_column('spec',
               existing_type=sa.Text(length=655360),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='配置详情',
               existing_nullable=True)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.alter_column('pipeline_file',
               existing_type=sa.Text(length=655360),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='workflow yaml',
               existing_nullable=True)

    with op.batch_alter_table('pytorchjob', schema=None) as batch_op:
        batch_op.alter_column('spec',
               existing_type=sa.Text(length=655360),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='配置详情',
               existing_nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.alter_column('parameter',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='前端保留参数，用于记录编排样式',
               existing_nullable=True)
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)
        batch_op.alter_column('pipeline_file',
               existing_type=sa.Text(length=655360),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='workflow yaml文件',
               existing_nullable=True)

    with op.batch_alter_table('notebook', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('metadata_table', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('metadata_metric', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)
        batch_op.alter_column('remark',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('caliber',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='数据负责人',
               existing_nullable=True)

    with op.batch_alter_table('job_template', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('inferenceservice', schema=None) as batch_op:
        batch_op.alter_column('deploy_history',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='部署历史',
               existing_nullable=True)
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)
        batch_op.alter_column('metrics',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='监控接口',
               existing_nullable=True)
        batch_op.alter_column('inference_config',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='配置文件',
               existing_nullable=True)
        batch_op.alter_column('model_output',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='模型输出',
               existing_nullable=True)
        batch_op.alter_column('model_input',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='模型输入',
               existing_nullable=True)

    with op.batch_alter_table('etl_task', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)
        batch_op.alter_column('task_args',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='任务参数',
               existing_nullable=True)

    with op.batch_alter_table('etl_pipeline', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)
        batch_op.alter_column('config',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='pipeline的全局配置',
               existing_nullable=True)
        batch_op.alter_column('dag_json',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='pipeline的上下游关系',
               existing_nullable=True)

    with op.batch_alter_table('docker', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.alter_column('expand',
               existing_type=sa.Text(length=65536),
               type_=mysql.MEDIUMTEXT(),
               existing_comment='扩展参数',
               existing_nullable=True)

    with op.batch_alter_table('ab_user', schema=None) as batch_op:
        batch_op.drop_column('ls_user_id')

    # ### end Alembic commands ###
